//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sClusterConnector) DeepCopyInto(out *K8sClusterConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sClusterConnector.
func (in *K8sClusterConnector) DeepCopy() *K8sClusterConnector {
	if in == nil {
		return nil
	}
	out := new(K8sClusterConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K8sClusterConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sClusterConnectorList) DeepCopyInto(out *K8sClusterConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K8sClusterConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sClusterConnectorList.
func (in *K8sClusterConnectorList) DeepCopy() *K8sClusterConnectorList {
	if in == nil {
		return nil
	}
	out := new(K8sClusterConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K8sClusterConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sClusterConnectorObservation) DeepCopyInto(out *K8sClusterConnectorObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sClusterConnectorObservation.
func (in *K8sClusterConnectorObservation) DeepCopy() *K8sClusterConnectorObservation {
	if in == nil {
		return nil
	}
	out := new(K8sClusterConnectorObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sClusterConnectorParameters) DeepCopyInto(out *K8sClusterConnectorParameters) {
	*out = *in
	if in.OrgId != nil {
		in, out := &in.OrgId, &out.OrgId
		*out = new(string)
		**out = **in
	}
	if in.ProjectId != nil {
		in, out := &in.ProjectId, &out.ProjectId
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DelegateSelectors != nil {
		in, out := &in.DelegateSelectors, &out.DelegateSelectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MasterUrl != nil {
		in, out := &in.MasterUrl, &out.MasterUrl
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sClusterConnectorParameters.
func (in *K8sClusterConnectorParameters) DeepCopy() *K8sClusterConnectorParameters {
	if in == nil {
		return nil
	}
	out := new(K8sClusterConnectorParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sClusterConnectorSpec) DeepCopyInto(out *K8sClusterConnectorSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sClusterConnectorSpec.
func (in *K8sClusterConnectorSpec) DeepCopy() *K8sClusterConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(K8sClusterConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sClusterConnectorStatus) DeepCopyInto(out *K8sClusterConnectorStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sClusterConnectorStatus.
func (in *K8sClusterConnectorStatus) DeepCopy() *K8sClusterConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(K8sClusterConnectorStatus)
	in.DeepCopyInto(out)
	return out
}
